[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
# These should be set in Railway dashboard
# PERPLEXITY_API_KEY = "your_key_here"